# Zero-Clause BSD License
# Copyright (C) 2024 Toitware ApS.

name: CI

on:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-14 ]

    name: CI - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: toitlang/action-setup@v1

      - name: Test
        run: make test
